name: build_and_deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout branch
      uses: actions/checkout@v1

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install numpy==1.16.5 # to resolve pandas install issue for now...
        pip install twine==1.15.0
        pip install -r requirements.txt

    - name: Build the Python package
      run: python setup.py bdist_wheel

    - name: Deploy the Python package
      if: success()
      run: python -m twine upload -u penuts7644 -p {{ secrets.PYPI_DEPLOY_KEY }} dist/*
