name: documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  documentation:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout branch
      uses: actions/checkout@v1

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install numpy==1.16.5 # to resolve pandas install issue for now...
        pip install sphinx==1.8.5
        pip install sphinx-rtd-theme>=0.4.3
        pip install -r requirements.txt

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub pages
      if: success()
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_build/html
